version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.0
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            sudo pip install praw==3.6.0
      - run:
          command: |
            python3 -m unittest tests/PIBotTests.py

